export const primaryColor = '#041833';
export const secondaryColor = '#0a2c5a';
export const tertiaryColor = '#08458f';
export const fourthColor = '#1875E8';
export const mainFontColor = '#041833';
export const pageFontColor = '#444444';
export const whiteColor = '#FFF';
export const mainFont = "'Raleway', sans-serif";
export const secondaryFont = "'Playfair Display', sans-serif";
